In [4]:
import pandas as pd

In [8]:
df = pd.read_csv('./merged_sheets_cp949.csv', encoding='cp949')
df

,부산구별,날짜,음식점 수,주점 수,버스 정류장 개수,지하철역 개수,지역구별 인구수,지역구 별 인구 대비 남자 수,가로등 수,CCTV 개수,횡단보도 개수,신호등 개수,주차장 개수,차량 등록 대수,택시 정류장 수,강수,기온,음주운전 사고건수,음주운전 단속건수
0,강서구,2021-01-01,1713,148,1091,3,138563,51.678298,20454,352,559,284,27,82033,2,34.8,2.0,51,30
1,금정구,2021-01-01,2011,315,500,7,231758,48.841895,6196,403,172,30,45,88419,5,56.5,2.9,36,26
2,기장군,2021-01-01,2026,176,774,2,175384,49.514209,15372,344,331,288,29,81674,10,50.5,3.5,40,16
3,남구,2021-01-01,2073,387,528,6,267217,48.937380,4624,351,237,26,25,99834,9,52.5,3.3,35,26
4,동구,2021-01-01,971,228,248,6,88662,48.984909,3649,374,82,16,67,52847,13,49.0,3.5,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,수영구,2023-12-01,2454,582,239,7,174493,46.932542,3459,348,119,11,10,125428,7,96.0,5.6,40,30
572,연제구,2023-12-01,2204,571,318,8,205747,47.797052,4343,365,171,46,25,129145,12,104.5,6.5,25,24
573,영도구,2023-12-01,1113,319,403,0,106529,49.108693,3359,377,118,15,37,34210,1,102.8,6.5,16,14
574,중구,2023-12-01,1411,588,126,3,38600,48.450777,1732,381,83,10,29,40840,12,102.8,6.5,1,9
575,해운대구,2023-12-01,3884,715,600,10,380390,47.918978,11159,337,503,41,40,180429,39,96.0,6.1,61,36

In [14]:
# 날짜를 datetime 형식으로 변환
df['날짜'] = pd.to_datetime(df['날짜'])

# 연도와 월 컬럼 추가
df['연도'] = df['날짜'].dt.year
df['월'] = df['날짜'].dt.month

# 2021, 2022, 2023 년도 데이터 필터링 (추가 데이터가 있을 경우 확장 가능)
filtered_df = df[df['연도'].isin([2021, 2022, 2023])]

# 구별, 연도별, 월별 음주운전 단속 건수 평균 계산
result = filtered_df.groupby(['부산구별', '연도'])['음주운전 단속건수'].mean().reset_index()

# 결과를 원하는 형식으로 변환
def format_output(row):
    return f"{row['부산구별']} {row['연도']} {row['음주운전 단속건수']}건"

result['결과'] = result.apply(format_output, axis=1)

# 결과 출력
for row in result['결과']:
    print(row)

강서구 2021 29.75건
강서구 2022 36.75건
강서구 2023 32.0건
금정구 2021 33.25건
금정구 2022 38.25건
금정구 2023 38.166666666666664건
기장군 2021 37.416666666666664건
기장군 2022 46.333333333333336건
기장군 2023 44.583333333333336건
남구 2021 35.166666666666664건
남구 2022 43.666666666666664건
남구 2023 43.0건
동구 2021 14.5건
동구 2022 11.25건
동구 2023 10.166666666666666건
동래구 2021 33.083333333333336건
동래구 2022 32.166666666666664건
동래구 2023 24.583333333333332건
부산진구 2021 42.583333333333336건
부산진구 2022 42.5건
부산진구 2023 44.166666666666664건
북구 2021 22.75건
북구 2022 25.5건
북구 2023 23.333333333333332건
사상구 2021 29.916666666666668건
사상구 2022 31.666666666666668건
사상구 2023 35.833333333333336건
사하구 2021 33.75건
사하구 2022 29.583333333333332건
사하구 2023 30.583333333333332건
서구 2021 7.333333333333333건
서구 2022 15.583333333333334건
서구 2023 14.5건
수영구 2021 27.083333333333332건
수영구 2022 29.833333333333332건
수영구 2023 28.666666666666668건
연제구 2021 30.916666666666668건
연제구 2022 26.583333333333332건
연제구 2023 25.25건
영도구 2021 15.5건
영도구 2022 21.083333333333332건
영도구 2023 18.666666666666668건
중구 2021 6.583333333333333건
중구 2022 8.583333333333334건
중구 2023 8.666666666666666건
해운대구 2021 40.916666666666664건
해운대구 2022 45.916666666666664건
해운대구 2023 43.583333333333336건

In [18]:
# 결과를 CSV 파일로 저장
result = result.drop(columns='결과')
result.to_csv("monthly_dui_analysis.csv", index=False, encoding='cp949')